import requests
import os
os.system
('clear')
('pip install requests')
num=input('اكتب رقم الهاتف: ')

headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
    
    'Host': 'ibiza.ooredoo.dz',
    'Connection': 'Keep-Alive',
    
    'User-Agent': 'okhttp/4.9.3',
}

data = {
    'client_id': 'ibiza-app',
    'grant_type': 'password',
    'mobile-number': num,
    'language': 'AR',
}

response = requests.post('https://ibiza.ooredoo.dz/auth/realms/ibiza/protocol/openid-connect/token', headers=headers, data=data)
print(response.text)
if 'ROOGY' in response.text:
    print('بعتولك كود')

otp=input('ابعت الكود لي جاك : ')
headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
    
    'Host': 'ibiza.ooredoo.dz',
    'Connection': 'Keep-Alive',
    
    'User-Agent': 'okhttp',
}

data = {
    'client_id': 'ibiza-app',
    'otp': otp,
    'grant_type': 'password',
    'mobile-number': num,
    'language': 'AR',
}

response = requests.post('https://ibiza.ooredoo.dz/auth/realms/ibiza/protocol/openid-connect/token', headers=headers, data=data)
access_token = response.json()['access_token']
print(response.text)
import requests




url = 'https://ibiza.ooredoo.dz/api/v1/mobile-bff/users/mgm/info/apply'

headers = {
    'Authorization': f'Bearer {access_token}',
    'language': 'AR',
    'request-id': 'ef69f4c6-2ead-4b93-95df-106ef37feefd',
    'flavour-type': 'gms',
    'Content-Type': 'application/json'
}

payload = {
    "mgmValue": "ABC"  
}



while True:
    response = requests.post(url, headers=headers, json=payload)
    if 'EU1002' in response.text:
        print ('بعتنالك كونكسيو')
    
    else:
        print('درك عندك كونكسيو ماتبقاش تعاود')

